### ISSUE TITLE
BLT deployments through Travis CI not working since 8.6.13

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt#1120]
My system information:
* Operating system type: macOS
* Operating system version: 10.12.3
* BLT version: 8.6.13

When I run this command:

* Deploy code to master (through merge or pushing a commit) on a GitHub project with Travis CI integration set up.

I get the following output:

```
blt > tests:run-server:kill:
     [exec] Executing command: pkill -f runserver
blt > tests:all:
blt > ci:build:validate:test:
BUILD FINISHED; 7 minutes  38.46 seconds
The command "source $BLT_DIR/scripts/travis/run_tests" exited with 0.
cache.2

dpl.0
Fetching: dpl-1.8.31.gem (100%)
Successfully installed dpl-1.8.31
1 gem installed

dpl.1
Installing deploy dependencies
!!! Script support is experimental !!!

dpl.2
Preparing deploy

dpl.3
Deploying application
Script failed with status 127
failed to deploy
```

And I expected this to happen:

The deployment should work like before (when it used `after_success`, I think).

## Notes

* This may be related to this Travis CI issue: https://github.com/travis-ci/travis-ci/issues/5538
* I did regenerate the `.travis.yml` file after upgrading (using `ci:travis:init`).
* I do have the proper `ssh_known_hosts` configured.
* There is no other error output before the 'Script failed with status 127' message.

**Comment by geerlingguy** [comment]
Some fixes I'm going to try:

  - [ ] [Add quotes](https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-220135972) around the `deploy.script` value.
  - [ ] [Manually run a `chmod`](https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-265956466) before sourcing the script.
  - [ ] [Check the pathing](https://github.com/travis-ci/travis-ci/issues/5538#issuecomment-225025939) when doing deploys.
  - [ ] Use `sh` or something other than `source` to include the file.
  - [ ]

**Comment by geerlingguy** [comment]
See above PR—basically, dropping the `source` and quoting everything made the deploy work. With `source`, it failed silently with the `127` error.
