### ISSUE TITLE
Better support using BLT for testing core and contrib with PHPUnit.

### ISSUE THREAD

**Issue by greylabel** [acquia/blt#1787]
It would be nice to have better support, documentation, and configurations for using BLT to _Run All PHPUnit Tests The Way The Testbot Does It_™, including kernel tests and browser tests.

- [x] Add setup instructions for PHPStorm + PHPUnit (#3198).
- [ ] Add new task that supports passing addition arguments to `phpunit` (#3249).
- [ ] Add command to set environment variables need for Drupal testing (#3249).
- [ ] Add new task and command to run Drupal's `run-tests.sh` (#3249).
- [ ] Instantiate `chromedriver` for function JavaScript testing (#3249).
- [ ] Decide on final schema for testing commands and refactor (#1524 and #3249).

**Comment by timcosgrove** [comment]
One thing I'm running into playing with this is, we definitely want BLT to be able to interoperate with Drupal 8.4.x in this scenario, so that we can run tests against the same Drupal D.O. does.

The main conflict between the two seems to be in the version of symfony/yaml. drupal/core 8.4.x specifies ^3.2, while both acquia/blt and grasmash/yaml-cli specify ~2.8, probably in line with what drupal/core 8.3.x specified.

Would moving acquia/blt and grasmash/yaml-cli to symfony/yaml ^3.2 be a breaking change?

**Comment by timcosgrove** [comment]
Extremely anecdotally, I can get a composer update/install working and then things going again by:

* updating yaml-cli symfony dependencies to 3.2 (https://github.com/timcosgrove/yaml-cli/tree/feature/symfony-3.2)
* updating blt symfony dependencies to 3.2 and drush to 9.x (https://github.com/timcosgrove/blt/tree/testing-symfony-3.2)
* point to these repos + drupal/core 8.4.x (local BLTED8 project)
* modify drush.wrapper to point to vendor/drush/drush/drush (local BLTED8 project)

yaml-cli and blt run their tests without issue with the new dependencies.  I realize this is not proper usability/functional testing, but it is a start.

I also remember the issues w/ drush 9.x and Acquia, so this might be a non-starter.

**Comment by grasmash** [comment]
We can modify BLT's version constraints to allow `^2.8|^3.2`. That should work. Otherwise, we would need to start a 8.10.x, to be released when 8.4.0 is cut.

**Comment by grasmash** [comment]
@greylabel Adding:

```
phpunit:
  - path: '${docroot}/core'
```

To blt/project.yml permits you to execute PHP unit tests from Drupal core.

What specific capabilities would you like to see added to BLT to improve the support?

**Comment by greylabel** [comment]
@grasmash I will review this in a bit and write up my thoughts more completely.

**Comment by greylabel** [comment]
I found a some time to revisit this issue.

For reference: https://www.drupal.org/docs/8/phpunit/running-phpunit-tests

1. The first potential challenge to testing with BLT is making sure you have the correct development dependencies installed. Often, we would want to test against a development snapshot of core or contrib vs a tagged release and may need packages installed with `composer install --dev` or other methods.
1. Next, BLT's `PhpUnitCommand` seems a little buggy and does not include support for passing the `testsuite` option to the `phpunit` bin. PR: [#1960](https://github.com/acquia/blt/pull/1960)
1. Finally, to run kernel test and browser tests, you need to copy core's `phpunit.xml.dist` to `phpunit.xml` and edit this file to set `SIMPLETEST_DB` and `SIMPLETEST_BASE_URL` or do so in your shell. We should probably automate the generation of these files. I only tested running phpunit from inside the VM as it needed a database connection string.

I still need to look at [PHPUnit Javascript testing](https://www.drupal.org/docs/8/phpunit/phpunit-javascript-testing-tutorial)

**Comment by dpagini** [comment]
> Finally, to run kernel and browser tests, you need to copy core's phpunit.xml.dist to phpunit.xml and edit this file to set SIMPLETEST_DB and SIMPLETEST_BASE_URL or do so in your shell. We should probably automate the generation of this file. I only tested running phpunit from inside the VM. Not sure if we care about support for tests being run outside the VM as tests:all already specifies @executeInDrupalVm.

@greylabel Instead of copying the file over, can't we just use the core dist file, and just provide those variables on top of it? Maybe BLT could allow you to specify those in the `blt/project.yml` file?

So maybe it would look something like...
```
phpunit:
  - path: '${docroot}/core'
    config: '${docroot}/core/phpunit.xml.dist'
    var:
      SIMPLETEST_DB: 'http://root@root:localhost/drupal'
      SIMPLETEST_BASE_URL: {$project.local.uri}
```
And then the BLT PHPUnit command can set those variables right before it runs the core test commands...?

Thoughts?

**Comment by greylabel** [comment]
Yea, this or something similar that realizes the same end goal of being able to run kernel and browser tests would be fine. We should think about how it would work in multisite context too.

**Comment by dpagini** [comment]
I've been playing around with this a little to try and get my local working... so I'm a little new to using the core tests (or any tests really). Should core tests be run against your main URL? and main database? or should they have their own?

Anyways, if the above were in place (PHPUnitCommand could set env variables before running), it seems like we would only need documentation after that to run a core test...? Is that fair to say? The multisite is definitely an issue as well.

**Comment by dpagini** [comment]
I spent some time this week looking at this, and wanted to share some more of my findings... sorry for the long post I'm about to write! I'm still pretty new to this testing, so please correct me where I get something wrong! My project is still on `8.9.12` so I see there are some more updates to `9.x`.

First, I was confused about running PHPUnit directly vs calling Drupal's `./core/scripts/run-tests.sh` utility. I still am somewhat. I found the [running your contrib tests](https://www.drupal.org/node/2469723) section stating you can use either. I'm guessing calling the scripts takes care of the config and variables for you...
So I think most of the suggestions above are around using the existing PHPUnitCommand to run tests, but I am leaning towards thinking this should be it's own _new_ command... or maybe use additional config somehow. Running Drupal tests I think needs 5 additional things that PHPUnitCommand is not providing now...
1. Install Simpletest module before testing. Simpletest is deprecated, but still present in core and contrib and many tests rely on its classes/methods. Would need to `.gitignore` the `docroot/sites/simpletest` folder.
1. Simpletest requires `docroot/sites/default/default.settings.php` file, which I believe is not present in a default BLT install due to `composer.required.json`. Maybe a copy command to create this file, and gitignore it...?
1. A way to set the url/db settings. This can be done via `phpunit.xml` file, passed via parameters to `./core/scripts/run-tests.sh`, or set directly on the command line via `export`, I believe. I think the last two are the _easier_ methods... depends if the command runs PHPUnit directly or calls the script. Setting the URL is pretty straightforward, but the database command isnt. How can we get that? Maybe via drush? It would obviously be good to avoid duplicating those credentials.
1. Run an optional webserver. I was thinking the new command uses the `@launchWebServer` annotation directives, among some others (Db check, run in VM, ensure drupal is installed, etc).
1. PhantomJS setup/configuration. (_haven't touched this one yet_)

**Given the above 5 things are correct, I think that's a lot of overhead to put on the base PHPUnitCommand. If I _just_ want to run some unit tests that don't need any of those dependencies, it's a lot to enable/configure all of that for what should be a simple command.**

So I'm not sure of the best way to implement this... I have something running locally which is a new `tests:drupal` target and copies MOST of the PHPUnitCommand but adds in some additional steps. I had a hard time "extending" the base command. I think it's my unfamiliarity with Robo/annotations.

**Comment by dpagini** [comment]
Here is my custom command which is working OK for me so far (no PhantomJS yet)... I keep my `default.settings.php` at `docroot/sites/all/` so the settings command here needs a little work....

https://gist.github.com/dpagini/3a2c49ade20a521b2b6eec7df0f43876

If my above approach sounds OK, and this command is a good starting point, I'm happy to post as a PR... LMK.

**Comment by malikkotob** [comment]
The changes from https://github.com/acquia/blt/pull/1960 seem to be causing issues for me after upgrading from `8.9.12` to `9.0.3`. Running `blt tests:phpunit` results in:
```
Cannot open file "ExampleTest.php".

[Testing\PHPUnit]  Exit code 1  Time 1.425s
[error]  PHPUnit tests failed.
```

It seems the 'file' definition in the `build.yml` file needs to contain the full path to the file:
```
phpunit:
  - path: '${repo.root}/tests/phpunit'
    class: 'ExampleTest'
    file: '${repo.root}/tests/phpunit/ExampleTest.php'
    config: null
```
vs. what is currently there:
```
phpunit:
  - path: '${repo.root}/tests/phpunit'
    class: 'ExampleTest'
    file: 'ExampleTest.php'
    config: null
```

I can submit a PR to fix it, but I'm confused as to why it was introduced. It seems a bit odd that the default behavior is to the Example Test file.

**Comment by danepowell** [comment]
On the very minor point of how to install composer dev dependencies ordinarily provided by Drupal core, I think the simplest approach is just to mirror these dependencies in BLT. Sadly this won't work for contrib modules, but it's a start. We have precedent for this: #3008, #1725 

There is also a tangentially related issue here that might be worth considering in this larger context: #3007
